// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type capture_sslEncDataEventT struct {
	TimestampNs uint64
	Pid         uint32
	Tid         uint32
	Data        [4096]uint8
	DataLen     int32
	_           [4]byte
}

// loadCapture_ssl returns the embedded CollectionSpec for capture_ssl.
func loadCapture_ssl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Capture_sslBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load capture_ssl: %w", err)
	}

	return spec, err
}

// loadCapture_sslObjects loads capture_ssl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*capture_sslObjects
//	*capture_sslPrograms
//	*capture_sslMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCapture_sslObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCapture_ssl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// capture_sslSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type capture_sslSpecs struct {
	capture_sslProgramSpecs
	capture_sslMapSpecs
}

// capture_sslSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type capture_sslProgramSpecs struct {
	FentryRead                  *ebpf.ProgramSpec `ebpf:"fentry_read"`
	ProbeEntryEVP_EncryptUpdate *ebpf.ProgramSpec `ebpf:"probe_entry_EVP_EncryptUpdate"`
}

// capture_sslMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type capture_sslMapSpecs struct {
	EventsRingbuf *ebpf.MapSpec `ebpf:"events_ringbuf"`
	PtrToFd       *ebpf.MapSpec `ebpf:"ptr_to_fd"`
}

// capture_sslObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCapture_sslObjects or ebpf.CollectionSpec.LoadAndAssign.
type capture_sslObjects struct {
	capture_sslPrograms
	capture_sslMaps
}

func (o *capture_sslObjects) Close() error {
	return _Capture_sslClose(
		&o.capture_sslPrograms,
		&o.capture_sslMaps,
	)
}

// capture_sslMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCapture_sslObjects or ebpf.CollectionSpec.LoadAndAssign.
type capture_sslMaps struct {
	EventsRingbuf *ebpf.Map `ebpf:"events_ringbuf"`
	PtrToFd       *ebpf.Map `ebpf:"ptr_to_fd"`
}

func (m *capture_sslMaps) Close() error {
	return _Capture_sslClose(
		m.EventsRingbuf,
		m.PtrToFd,
	)
}

// capture_sslPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCapture_sslObjects or ebpf.CollectionSpec.LoadAndAssign.
type capture_sslPrograms struct {
	FentryRead                  *ebpf.Program `ebpf:"fentry_read"`
	ProbeEntryEVP_EncryptUpdate *ebpf.Program `ebpf:"probe_entry_EVP_EncryptUpdate"`
}

func (p *capture_sslPrograms) Close() error {
	return _Capture_sslClose(
		p.FentryRead,
		p.ProbeEntryEVP_EncryptUpdate,
	)
}

func _Capture_sslClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed capture_ssl_x86_bpfel.o
var _Capture_sslBytes []byte
